site_name: Liferay Challenge Docs

repo_url: https://github.com/nananananate/liferay-challenge
repo_name: nananananate/liferay-challenge

theme:
  name: material



markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets:
      base_path: docs/
#  - markdown_include.include:
#      base_path: docs

extra_css:
  - css/termynal.css

extra_javascript:
  - js/termynal.js
  - js/custom.js
